### ISSUE TITLE
RunCollection.m: gpu_list is not passed to run_lfads_queue

### ISSUE THREAD

**Issue by cpandar** [djoshea/lfads-run-manager#2]
in RunCollection.m:

gpuListStr is calculated in lines 305-310, and is properly output to run_lfadsqueue.py so that the variable is defined in the script

However, this variable is never actually passed to the command lq.run_lfads_queue on line 345

The following replacement for line 345 fixes the issue:

`fprintf(fid, 'tasks = lq.run_lfads_queue(queue_name, tensorboard_script, task_specs, gpu_list=gpu_list%s%s)\n\n', maxStr, donefileStr);`

**Comment by djoshea** [comment]
Thanks Chethan, this should now be fixed via 870d574. I've also added the flag `oneTaskPerGPU`, which defaults to true. This defaults to run one model on each GPU, rather than squeezing as many onto each GPU as the available memory will support.
